// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPepmwA2tI-L4HamIaItvNRByw3vbfcvY',
    appId: '1:377134130294:android:fe20c46747dd2b2ede2b57',
    messagingSenderId: '377134130294',
    projectId: 'fintrack-finance',
    storageBucket: 'fintrack-finance.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn4r9_T5-UVbZNelm0EWjunew_lc4ICh0',
    appId: '1:377134130294:web:4601ca0e8d9e8aa3de2b57',
    messagingSenderId: '377134130294',
    projectId: 'fintrack-finance',
    authDomain: 'fintrack-finance.firebaseapp.com',
    storageBucket: 'fintrack-finance.firebasestorage.app',
    measurementId: 'G-TR2Q123M67',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn4r9_T5-UVbZNelm0EWjunew_lc4ICh0',
    appId: '1:377134130294:web:4601ca0e8d9e8aa3de2b57',
    messagingSenderId: '377134130294',
    projectId: 'fintrack-finance',
    authDomain: 'fintrack-finance.firebaseapp.com',
    storageBucket: 'fintrack-finance.firebasestorage.app',
    measurementId: 'G-TR2Q123M67',
  );

}